#690: Added mirrors for Rancher Desktop
devonfw/ide-mirrors pull request #13
Opened 2022-03-23 13:46 UTC by cinnamon-coder-hub

2022-04-04 08:05 UTC, hohwille requested changes

2022-04-04 08:05 UTC, hohwille commented on rancher/urls
> +https://github.com/rancher-sandbox/rancher-desktop/releases/download/v${version}/Rancher.Desktop-${version}.${arch}.${ext}
This looks awkward.
IMHO these are not two different mirrors but two different URL schemas where only one of the two will actually work so by random we have a 50:50 chance to first hit the wrong URL.
Is that because of
* [rancher-desktop-linux-v1.2.0.zip](https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.2.0/rancher-desktop-linux-v1.2.0.zip)
* [Rancher.Desktop.Setup.1.2.0.exe](https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.2.0/Rancher.Desktop.Setup.1.2.0.exe)
* [Rancher.Desktop-1.2.0-mac.x86_64.zip](https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.2.0/Rancher.Desktop-1.2.0-mac.x86_64.zip)

Actually it seems that (as in most cases) the providers of such products have no reasonable naming conventions for their downloads. According to the above links, I still do not see how you would match all the three examples with this two URL patterns.
Do we need to extend devonfw-ide in general to allow even more flexible URL patterns?
With reasonable programming languages (like Java, C#, Ruby, etc.) it would be no problem to do this but with bash this is already tricky enough...

2022-04-05 09:51 UTC, cinnamon-coder-hub commented on rancher/urls
> +https://github.com/rancher-sandbox/rancher-desktop/releases/download/v${version}/Rancher.Desktop-${version}.${arch}.${ext}
Right. Now that I have a proper understanding of the purpose I revised the code. We have one mirror-URL now. It does not look pretty, but it works and should be rather easy to edit in the case that the URLs structure changes.

2022-04-05 13:09 UTC, hohwille approved these changes
@cinnamon-coder-hub thanks for the update.
Your os-mappings seems like the perfect soluttion.
I hope that x86_64 is not an issue for windows.
So lets merge and test it.

2022-04-05 13:10 UTC, merged